FROM ubuntu:16.04

RUN apt-get update && apt-get install -y git build-essential \
  automake autotools-dev fuse g++ git libcurl4-openssl-dev \
  libfuse-dev libssl-dev libxml2-dev make pkg-config


RUN git clone https://github.com/s3fs-fuse/s3fs-fuse.git && \
    cd s3fs-fuse && \
    ./autogen.sh && \
    ./configure && \
    make && \
    make install
